//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTB
    {
        public int ID { get; set; }
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public string Email { get; set; }
    }
}
