//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public string ManagerName { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public decimal ActualHours { get; set; }
        public decimal WorkingHours { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int salary { get; set; }
        public int gender { get; set; }
        public bool IsActive { get; set; }
        public string Certificate { get; set; }
        public string emailId { get; set; }
    }
}
