//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table4
    {
        public int Id { get; set; }
        public Nullable<int> TestData1 { get; set; }
        public Nullable<double> TestData2 { get; set; }
        public string Name { get; set; }
    }
}
